import { Plus_Jakarta_Sans } from "next/font/google";
import "./global.css";
import QueryProvider from "./admin/providers/QueryProvider";
import ReduxProvider from "./admin/providers/ReduxProvider";
import { ToastProvider } from "./admin/components/ToastProvider";
import { SatoshiCustom } from "./admin/fonts/font";

const JakartaSans = Plus_Jakarta_Sans({
  variable: "--font-jakarta-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Capsa App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      suppressHydrationWarning
        className={`${JakartaSans.variable} ${SatoshiCustom.variable} bg-white font-sans antialiased`}
      >
         <QueryProvider>
          <ReduxProvider>
            {children}
            <ToastProvider/>
          </ReduxProvider>
        </QueryProvider>
      </body>
    </html>
  );
}